{
 "title": "polymarket-arbitrage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (cik) (increase(edgar_rss_feed_submitions_total[$__range])))",
     "legendFormat": "CIK: {{cik}}"
    }
   ]
  },
  {
   "title": "Python version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "python_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Total EDGAR submitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(edgar_rss_feed_submitions_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total oracle resolutions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(oracle_resolution_total{outcome=\"Yes\"})",
     "legendFormat": "Yes"
    },
    {
     "expr": "sum(oracle_resolution_total{outcome=\"No\"})",
     "legendFormat": "No"
    }
   ]
  },
  {
   "title": "Total earned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(polymarket_usd_earned_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currently watched markets",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "polymarket_watched_markets_total == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (ticker, slug) (polymarket_market_volume_usd_total and on (ticker) (polymarket_watched_markets_total == 1))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (ticker) (polymarket_usd_earned_total and on (ticker) (polymarket_watched_markets_total == 1))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (ticker) (oracle_resolution_time_seconds and on (ticker) (polymarket_watched_markets_total == 1))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (ticker, outcome) (oracle_resolution_total and on (ticker) (polymarket_watched_markets_total == 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed EDGAR submissions",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(edgar_rss_feed_submitions_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}